version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - '3001:3001'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: news_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
